version: '3.8'
services:
  gateway:
    build: /shareIt-gateway
    image: gateway_image
    container_name: gateway_container
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: /shareIt-server
    image: server_image
    container_name: server_container
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - BD=jdbc:postgresql://localhost:5433/postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass

  db:
    image: postgres:13.7-alpine
    container_name: some_postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - DB_HOST=localhost
      - DB_PORT=5432