CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(255),
    email VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS request
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255),
    user_id     BIGINT REFERENCES users (id),
    create      DATETIME
);

CREATE TABLE IF NOT EXISTS item
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255),
    description VARCHAR(255),
    available   BOOLEAN,
    user_id     BIGINT REFERENCES users (id),
    request_id  BIGINT REFERENCES request (id)
);

CREATE TABLE IF NOT EXISTS booking
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    starttime   DATETIME,
    endtime     DATETIME,
    item_id BIGINT REFERENCES item (id),
    user_id BIGINT REFERENCES users (id),
    status  VARCHAR(255)
);
