drop table if exists booking cascade;
drop table if exists comments cascade;
drop table if exists item cascade;
drop table if exists item_request cascade;

create table if not exists users
(
    id    bigint generated by default as identity,
    email varchar(255) unique,
    name  varchar(255),
    primary key (id)
    );
create table if not exists item_request
(
    create       timestamp(6),
    id           bigint generated by default as identity,
    requestor_id bigint unique ,
    description  varchar(255),
    primary key (id),
    foreign key (requestor_id) references users(id)
    );
create table if not exists item
(
    available   boolean,
    id          bigint generated by default as identity,
    owner_id    bigint,
    request_id  bigint,
    description varchar(255),
    name        varchar(255),
    primary key (id),
    foreign key (owner_id) references users(id),
    foreign key (request_id) references item_request(id)
    );
create table if not exists comments
(
    author_id bigint,
    created   timestamp(6),
    id        bigint generated by default as identity,
    item_id   bigint references item(id),
    text      varchar(255),
    primary key (id),
    foreign key (item_id) references item(id),
    foreign key (author_id) references users(id)
    );
create table if not exists booking
(
    id         bigint generated by default as identity,
    booker_id  bigint,
    end_time   timestamp(6),
    item_id    bigint,
    start_time timestamp(6),
    status     varchar(255) check (status in ('WAITING', 'APPROVED', 'REJECTED', 'CANCELED')),
    primary key (id),
    foreign key (booker_id) references users(id),
    foreign key (item_id) references item(id)

    );