CREATE TABLE IF NOT EXISTS user
(
    id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(255),
    email VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS request
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255),
    user_id     BIGINT REFERENCES user (id),
    create      DATETIME
);

CREATE TABLE IF NOT EXISTS item
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255),
    description VARCHAR(255),
    available   BOOLEAN,
    user_id     BIGINT REFERENCES user (id),
    request_id  BIGINT REFERENCES request (id),
);

CREATE TABLE IF NOT EXISTS booking
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start   DATETIME,
    end     DATETIME,
    item_id BIGINT REFERENCES item (id),
    user_id BIGINT REFERENCES user (id),
    status  VARCHAR(255)
);





